<scm class="hudson.plugins.git.GitSCM">
  <configVersion>1</configVersion>
  <remoteRepositories>
    <RemoteConfig>
      <name>origin</name>
      <uris>
        <org.eclipse.jgit.transport.URIish>
          <scheme>${scm.git.scheme}</scheme>
          <path>${scm.git.path}</path>
          <port>-1</port>
          <host>${scm.git.host}</host>
        </org.eclipse.jgit.transport.URIish>
      </uris>
      <pushURIs/>
      <fetch>
        <org.eclipse.jgit.transport.RefSpec>
          <force>true</force>
          <wildcard>true</wildcard>
          <srcName>refs/heads/*</srcName>
          <dstName>refs/remotes/origin/*</dstName>
        </org.eclipse.jgit.transport.RefSpec>
      </fetch>
      <push/>
      <uploadpack>git-upload-pack</uploadpack>
      <receivepack>git-receive-pack</receivepack>
      <tagopt>AUTO_FOLLOW</tagopt>
      <mirror>false</mirror>
      <timeout>0</timeout>
      <relativeTargetDir></relativeTargetDir>
    </RemoteConfig>
  </remoteRepositories>
  <branches>
    <hudson.plugins.git.BranchSpec>
      <name>${scm.git.branch}</name>
    </hudson.plugins.git.BranchSpec>
  </branches>
  <mergeOptions/>
  <recursiveSubmodules>false</recursiveSubmodules>
  <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
  <authorOrCommitter>false</authorOrCommitter>
  <clean>false</clean>
  <wipeOutWorkspace>false</wipeOutWorkspace>
  <pruneBranches>false</pruneBranches>
  <buildChooser class="hudson.plugins.git.util.DefaultBuildChooser"/>
  <gitTool>${scm.git.tool}</gitTool>
  <submoduleCfg class="list"/>
  <excludedRegions></excludedRegions>
  <excludedUsers></excludedUsers>
  <gitConfigName></gitConfigName>
  <gitConfigEmail></gitConfigEmail>
  <skipTag>false</skipTag>
</scm>
